name: Setup Environment
inputs:
  SECRET_GITHUB_TOKEN:
    required: true
    description: 'Github Secret Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ inputs.SECRET_GITHUB_TOKEN }}
